[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  VAR_TOML_FILE = "VAR_TOML_FILE_value"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Content-Security-Policy = "frame-ancestors *"
