[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
  TOML_FILE_VAR = "TOML_FILE_VAR_value"
  SITE_ENV_VAR = "Override"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Content-Security-Policy = "frame-ancestors *"
