[build]
  command = "npm run build"
  publish = "dist/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Content-Security-Policy = "frame-ancestors *"
